require 'twitter'

client = Twitter::REST::Client.new do |config|
  config.consumer_key        = ENV["CONSUMER_API_KEY"]
  config.consumer_secret     = ENV["CONSUMER_API_SECRET"]
  config.access_token        = ENV["ACCESS_TOKEN"]
  config.access_token_secret = ENV["ACCESS_SECRET"]
end

# trash tweets generated by:
# * downloading my archive from twitter
# * extracting and parsing tweets.js with jq:
#   cat tweet.json | jq '.[] | select(.created_at | strptime("%a %b %d
#   %H:%M:%S %z %Y") | mktime < 1558393200 ) | .id_str' >
#   trash_ids.txt
# * The magic number is the epoch time given by (Date.now -
# * 30).to_time.to_i in irb

me           = client.user
trash_tweets = File.readlines("trash_ids.txt", chomp: true).map(&:to_i)

trash_tweets.each_slice(100) do |slice|
  tweet_slice = slice.map { |t_id| Twitter::Tweet.new(id: t_id) }

  puts "destroying #{tweet_slice.count} tweets"
  client.destroy_status(client.statuses(tweet_slice))
end
